include:
  - component: $CI_SERVER_FQDN/dev-ops/templates/automatisation/ci-cd/pipeline-java-publish@~latest
    inputs:
      java_version: 11
      java_builder_build_image: gitlab-registry.ifremer.fr/ifremer-commons/docker/internal-images/maven:eclipse-temurin-11-alpine-javafx17
      java_builder_maven_settings_path: ci_settings.xml
      java_builder_tests_enable: true
      java_builder_artifacts_path: "**/target/*.[zip|jar]"
      quality_sonar_scanner_cli_opts: "-Dsonar.qualitygate.timeout=900"
      release_artifact_name: Version Windows 64 bit
      release_artifact_url: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/maven/fr/ifremer/octopus/$CI_COMMIT_TAG/octopus-$CI_COMMIT_TAG-Win.zip
      release_assets: |
        Version Windows 64 bit Standalone|${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/maven/fr/ifremer/octopus/$CI_COMMIT_TAG/octopus-$CI_COMMIT_TAG-Win_standalone.zip
        Version Linux|${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/maven/fr/ifremer/octopus/$CI_COMMIT_TAG/octopus-$CI_COMMIT_TAG-Linux.zip
        Version Linux Standalone|${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/maven/fr/ifremer/octopus/$CI_COMMIT_TAG/octopus-$CI_COMMIT_TAG-Linux64_standalone.zip
