include:
  - component: $CI_SERVER_FQDN/dev-ops/templates/automatisation/ci-cd/pipeline-java-publish@~latest
    inputs:
      java_version: 11
      java_builder_build_image: gitlab-registry.ifremer.fr/ifremer-commons/docker/internal-images/maven:eclipse-temurin-11-alpine-javafx17
      java_builder_maven_settings_path: ci_settings.xml
      java_builder_tests_enable: true
      java_builder_artifacts_path: "**/target/*.[zip|jar]"

# surcharge des assets de la release gitlab
release:gitlab:create 🚀:
  release:
    name: Release $MAVEN_RELEASE_VERSION
    description: $CI_COMMIT_TAG_MESSAGE
    tag_name: $MAVEN_RELEASE_VERSION
    ref: $CI_COMMIT_SHA
    assets:
      links:
        - name: octopus-$MAVEN_RELEASE_VERSION-Win64_standalone.zip
          url: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/maven/fr/ifremer/octopus/$MAVEN_RELEASE_VERSION/octopus-$MAVEN_RELEASE_VERSION-Win_standalone.zip"
        - name: octopus-$MAVEN_RELEASE_VERSION-Win.zip
          url: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/maven/fr/ifremer/octopus/$MAVEN_RELEASE_VERSION/octopus-$MAVEN_RELEASE_VERSION-Win.zip"
        - name: octopus-$MAVEN_RELEASE_VERSION-Linux64_standalone.zip
          url: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/maven/fr/ifremer/octopus/$MAVEN_RELEASE_VERSION/octopus-$MAVEN_RELEASE_VERSION-Linux64_standalone.zip"
        - name: octopus-$MAVEN_RELEASE_VERSION-Linux.zip
          url: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/maven/fr/ifremer/octopus/$MAVEN_RELEASE_VERSION/octopus-$MAVEN_RELEASE_VERSION-Linux.zip"